### ISSUE TITLE
Create/edit PostgreSQL database

### ISSUE THREAD

**Issue by ejd500** [ejd500/marthas-good-eats#1]
Create/edit PostgreSQL database for the mock data generated. Populate the database with Mock data.
- Tables include: Menu_Items and Registrations (or Logins)
- Registrations columns should include user_id (automatically generated), email, and password
- Menu_Items columns should include menu_id (automatically generated), name, description, price, category, and image_url

**Comment by CorinaJewer** [comment]
Created Users Table & Menu_Items tables under new database called 'marthas_good_eats' in PostgreSQL. Inserted all menu items. Updated all SQL statements under SQL folder.  Created the json folder under services and the INSERT_TABLE_Menu_Items.json for MongoDB. Added all images to public/images for the menu items. Amended getLoginByUsername to getLoginByEmail under ;pg.login.dal' so that we verify email against the new Users table now instead of username against Logins. Shared database restore.sql with Ellen.
