### ISSUE TITLE
Create MongoDB database

### ISSUE THREAD

**Issue by ejd500** [ejd500/marthas-good-eats#2]
Create MongoDB database for the mock data generated. Populate collections with Mock data.
- Collections include Menu_Items and Registrations
- Registrations should include user_id (automatically generated), email, and password
- Menu_Items should include menu_id (automatically generated), name, description, price, category, and image_url

**Comment by CorinaJewer** [comment]
- Created Mongo database titled "Restaurant" and collection "Menu_Items". 
- I did not create the Users collection as since we have decided to store our Users using PostgreSQL only and use that for our login system.
- "Menu_Items" collection includes ObjectId as _id, name, description, price, category, and image_url.
- Populated "Menu_Items" with same data as PostgreSQL table "Menu_Items".
